### ISSUE TITLE
Publish to Terraform Registry

### ISSUE THREAD

**Issue by mcmarkj** [everonhq/terraform-provider-ec#2]
As of terraform 0.13, you can publish community providers to the terraform registry. This massively simplifies the installation process for users. 

Opened this issue to ask if it's possible you publish the elastic cloud provider to the terraform registry? 😄 

https://www.terraform.io/docs/registry/modules/publish.html

**Comment by mcmarkj** [comment]
I've published this for now as it was blocking our migration to terraform 0.13
https://registry.terraform.io/providers/mcmarkj/ec/latest

**Comment by omelnyk1** [comment]
Hi @mcmarkj ,
Well done. We decided to use official elastic plugin: https://github.com/elastic/terraform-provider-ec and stop develop our own.

**Comment by mcmarkj** [comment]
Yeah @omelnyk1 - waiting for the first release of that provider before I switch over.

**Comment by omelnyk1** [comment]
BTW, someone already forked and published their plugin: https://registry.terraform.io/providers/alejandrod/ec/latest
